apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/pv0006
    type: DirectoryOrCreate