apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.8.50
    path: /nfs/pv0005