apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.8.50
    path: /nfs/pv0006