apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0011
  annotations:
    volume.beta.kubernetes.io/storage-class: "mongodb"
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.8.51
    path: /nfs/pv0011