apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/pv0003
    type: DirectoryOrCreate