apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/pv0004
    type: DirectoryOrCreate