apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/pv0002
    type: DirectoryOrCreate