apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  ports:
  - name: mongodb-service
    port: 27017
    protocol: TCP
    targetPort: 27017

  selector:
    app.kubernetes.io/name: mongodb-server
  type: LoadBalancer
  loadBalancerIP: "192.168.51.2"
status:
  loadBalancer: {}