apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  ports:
  - name: "argo-http"
    port: 80
    protocol: TCP
    targetPort: 8080

  selector:
    app.kubernetes.io/name: mongodb-server
  type: LoadBalancer
  loadBalancerIP: "192.168.51.2"
status:
  loadBalancer: {}