apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-api-cloudflared
spec:
  selector:
    matchLabels:
      name: debug-api-cloudflared
  template:
    metadata:
      labels:
        name: debug-api-cloudflared
    spec:
      containers:
        - env:
            - name: TUNNEL_NAME
              value: debug-api
            - name: CLOUDFLARED_HOSTNAME
              value: debug-api.purapetino.com
            - name: CLOUDFLARED_SERVICE
              value: http://dev-nginx-service.debug:80
          image: ghcr.io/purapetino/cloudflared-tunnel:1.0.2-2022.12.1
          name: debug-api-cloudflared
          resources:
            limits:
              cpu: 70m
              memory: 512Mi
          volumeMounts:
            - mountPath: /root
              name: cloudflared
      volumes:
        - name: cloudflared
          persistentVolumeClaim:
            claimName: cloudflared-pvc
status: {}