namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.4/manifests/install.yaml
  - configs/ingress.yaml
patches:
  - configs/install-patch.yaml
  - configs/argocd-cm.yaml
  - configs/argocd-repo-patch.yaml
  - configs/argocd-rbac-cm.yaml