apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crd
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/kube-prometheus-stack/crds/
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: 43.1.3
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 43.1.3

    helm:
      releaseName: prometheus
      skipCrds: true
      values: |
        defaultRules:
            rules:
              alertmanager: true
        grafana:
          defaultDashboardsTimezone: "Asia/Tokyo"
          plugins:
            - grafana-piechart-panel
          grafana.ini:
            server:
              enforce_domain: true
              domain: admin-grafana.purapetino.com
              root_url: https://%(domain)s/
            date_formats:
              default_timezone: Asia/Tokyo
            auth:
              disable_login_form: true
              oauth_auto_login: true
            auth:
              disable_login_form: true
              oauth_auto_login: true
            auth.github:
              enabled: true
              allow_sign_up: true
              client_id: client_id
              client_secret: client_key
              scopes: user:email,read:org
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              allowed_organizations: SharkDiscordBot
            security:
              cookie_secure: true
              strict_transport_security: true
              content_security_policy: true
          envFromSecret: "grafana-secret"
          persistence:
            enabled: true
            size: 5Gi
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://prometheus-kube-prometheus-prometheus:9090
                  isDefault: true


        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 10Gi
            resources:
              requests:
                memory: 2Gi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true