apiVersion: v1
kind: Service
metadata:
  name: hubble-service
  namespace: kube-system
spec:
  ports:
  - name: "ui"
    port: 80
    protocol: TCP
    targetPort: 4245

  selector:
    k8s-app: hubble-relay
  type: LoadBalancer
  loadBalancerIP: "192.168.51.2"
status:
  loadBalancer: {}