apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: ''
  policy.csv: |
    g, SharkDiscordBot:admin-team, role:admin

  policy.matchMode: 'glob'
  scopes: '[cognito:groups, email]'