apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, SharkDiscordBot:admin-team, role:admin
    g, $argocd-github-auth-secret:email, role:admin