apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server

  namespace: argocd
spec:
  ports:
  - name: "argo-http"
    port: 80
    protocol: TCP
    targetPort: 80
  - name: "argo-https"
    port: 443
    protocol: TCP
    targetPort: 443

  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
  loadBalancerIP: "192.168.51.1"
status:
  loadBalancer: {}