apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
spec:
  ports:
  - name: "argo-http"
    port: 80
    protocol: TCP
    targetPort: 80
  - name: "argo-https"
    port: 443
    protocol: TCP
    targetPort: 443

  selector:
    app: argocd-server
  type: LoadBalancer
  loadBalancerIP: "192.168.51.1"
status:
  loadBalancer: {}