# argocdのgithubログインに関するシークレット
# クラスタを再構築するタイミングがあればargocd自体にシークレットをもたせる
# TODO: argocd-cmに直接値を設定する

apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd"
type: Opaque
stringData:
  client_id: <client_id>
  client_key: <client_key>